Update patch set 2
Patch Set 2:

Seems to have failed again due to that keystore issue:

  com.android.ide.common.signing.KeytoolException: Failed to read key AndroidDebugKey from store "/home/android-build/.android/debug.keystore": X.5 not found

Patch-set: 2
Reviewer: Gerrit User 1590267 <1590267@85c56323-6fa9-3386-8a01-6480fb634889>